---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 6.2.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nginx
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx
  filterTags:
    pattern: '^stage.*'
  policy:
    alphabetical:
      order: desc
---
#apiVersion: image.toolkit.fluxcd.io/v1beta2
#kind: ImagePolicy
#metadata:
#  name: nginx
#  namespace: flux-system
#spec:
#  imageRepositoryRef:
#    name: nginx
#  filterTags:
#    pattern: 'stage*'
#  policy:
#    sort: custom
    #order: desc
#    sortBy: python3 ../../../custom_sort_ecr.py  # Reference the custom sorting script
  #schedule: "*/5 * * * *"---
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nginx1
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: 'stage*'
  imageRepositoryRef:
    name: nginx
  policy:
    alphabetical:
      order: desc
