apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: podinfo-config
    literals: 
      - uiColor="#96645E"
commonLabels:
  app: podinfo